language: python

python:
  - "2.7"
#  - "3.2"
#  - "3.3"

install:
    - pip install coverage
    - pip install coveralls

script:
    - python setup.py sdist --verbose
    - cd dist
    - pip install -vvv prompty*.tar.gz
    - python  ../test/test_prompty.py
    - pip uninstall -y prompty
    - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then cd ..; rm -f bin/promptyc; python -m coverage.__main__ run --source=prompty,test,bin/prompty test/test_prompty.py; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then python -m coverage.__main__ report; fi

after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then coveralls; fi

branches:
  only:
    - master
    - develop
