language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
    - pip install -r requirements.txt
    - pip install -r test/requirements.txt
    - pip install -r docs/requirements.txt
    - pip install coverage
    - pip install coveralls

script:
    - git fetch
    - python -m pytest
    - python setup.py sdist --verbose
    - cd dist
    - pip install -vvv prompty*.tar.gz
    - pip uninstall -y prompty
    - cd ..
    - rm -f bin/promptyc
    - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then python -m coverage.__main__ run --source=prompty,test,bin/prompty -m pytest; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then python -m coverage.__main__ report; fi

after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then coveralls; fi

branches:
  only:
    - master
    - develop
    - feature/.*
