language: python

python:
  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"

install:
    - pip install coverage
    - pip install coveralls

script:
    - python setup.py sdist --verbose
    - cd dist
    - pip install -vvv prompty*.tar.gz
    - python -m coverage.__main__ run --source=prompty,../test,$(which prompty) ../test/test_prompty.py
    - python -m coverage.__main__ report
    - pip uninstall -y prompty

after_success:
    coveralls

branches:
  only:
    - master
