language: python

python:
  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"

install:
    - pip install coveralls

script:
    python-coverage run --source=prompty,bin,test test/test_prompty.py

after_success:
    coveralls

branches:
  only:
    - master
