language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
    - pip install coverage
    - pip install coveralls
    - pip install future
    - pip install mock
    - pip install configparser
    - pip install pytest
    - pip install sphinx

script:
    - git fetch
    - python -m pytest
    - python setup.py sdist --verbose
    - cd dist
    - pip install -vvv prmpt*.tar.gz
    - pip uninstall -y prmpt
    - cd ..
    - rm -f bin/prmptc
    - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then python -m coverage.__main__ run --source=prmpt,test,bin/prmpt -m pytest; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then python -m coverage.__main__ report; fi

after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then coveralls; fi

branches:
  only:
    - master
    - develop
    - feature/.*
